#!/usr/bin/.env node

/**
 * Module dependencies.
 */
require('dotenv').config();

const {PostgresDatabase} = require("fast-express-backend/databases/postgresql");



var app = require('./app');



var debug = require('debug')('wechat:server');
var https = require('https');
const {Databases, DATABASE_TYPES} = require("fast-express-backend/databases");
const {registerAllTables} = require("./models");
const {WebSocketServer} = require("ws");
const {SocketHandler} = require("./handleChats");
const fs = require("fs")

async function setupDatabase(){
    const db = new PostgresDatabase();
    const {POSTGRESQL_DB_PORT ,POSTGRESQL_DB_NAME , POSTGRESQL_DB_HOST  ,POSTGRESQL_DB_USERNAME ,POSTGRESQL_DB_PASSWORD } = process.env;
   await  db.connect(
        POSTGRESQL_DB_HOST,
        POSTGRESQL_DB_USERNAME,
        POSTGRESQL_DB_PASSWORD,
        POSTGRESQL_DB_NAME,
       POSTGRESQL_DB_PORT
     )

    Databases.connections[DATABASE_TYPES.POSTGRES] = db;
   console.log("Good to go with database")
}


/**
 * Get port from environment and store in Express.
 */

var port = normalizePort(process.env.PORT || '3000');
app.set('port', port);

// Load SSL certs
const options = {
    key: fs.readFileSync('server.key'),
    cert: fs.readFileSync('server.cert'),
    minVersion: 'TLSv1.2'


};



/**
 * Create HTTP server.
 */

var server = https.createServer(options,app);

/**
 * Listen on provided port, on all network interfaces.
 */

async function onTheRun(){
    await setupDatabase();
    await registerAllTables(Databases.connections[DATABASE_TYPES.POSTGRES]);
    // app.use("/users",userRouter)
    server.listen(port);
    server.on('error', onError);
    server.on('listening', onListening);
    console.log("this was resta  rted")
}


function initWebSocketConnection(){

}


/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  debug('Listening on ' + bind);
}


const webSocketServer = new WebSocketServer({server})

webSocketServer.on('connection',function (socket) {
    try{
        const s = new SocketHandler(socket);
    }catch (e){
        console.log(e)
    }

})

onTheRun().then(e => {
    console.log(e)
}).catch(e => {
    console.log(e)
})

