const  MESSAGE_TYPES = {
    'SEND':0,
    'CREATE_ROOM':1,
    'ROOM_CREATED':2,
    'ROOM_CREATED_FAILED':3,
    'MESSAGE_RECEIVED':4,
    'SET_MESSAGE_DELIVERED':5,
    'MESSAGE_DELIVERED':6,
    'GET_BACK_CREATED_MESSAGE':7,
    'SET_LIST_OF_MESSAGE_DELIVERED':8,
    'RECEIVE_LIST_OF_MESSAGE_DELIVERED':9,
    'SET_SEEN_MESSAGE':10,
    'RECEIVE_SEEN_MESSAGE':11,
    'FILE_MESSAGE_SEND_TO_OTHER_USER':12,
    'FILE_MESSAGE_RECEIVE_TO_OTHER_USER':13,
}


const USER_HANDLES = {
    'NEW_CONNECTION':0,
    'REMOVE_CONNECTION': 1,
}



const MAIN_HANDLERS = {
    'USER_CONFIG':0,
    'FILE_SHARE':1,
    'MESSAGE':2,
    'CALL':3
}


const FILE_TYPES = {
    'FILE_CREATE':0,
    'FILE_CHUCK_TO_SERVER':1,
    'FILE_CHUCK_TO_CLIENT':2,
    'FILE_CHUCK_FINISHED':3,
    'FILE_CREATED':4
}

const ERRORS = {
    'ROOM_ALREADY_EXISTS':50
}


const CALL_TYPES = {
    'CALL_OFFER_CREATED':1,
    'CALL_OFFER_RECEIVED':2,
    'CALL_ANSWER_CREATED':3,
    'CALL_ANSWER_RECEIVED':4,
    'CALL_ICE_NEW_CANDIDATE_CREATED':5,
    'CALL_ICE_NEW_CANDIDATE_RECEIVED':6,
    'CALL_WAS_DISCONNECTED_BY_USER':7,
    'CALL_WAS_DISCONNECTED_BY_USER_RECEIVED':8,
}



module.exports = {MESSAGE_TYPES,MAIN_HANDLERS,ERRORS,USER_HANDLES,FILE_TYPES,CALL_TYPES}