const  MESSAGE_TYPES = {
    'SEND':0,
    'CREATE_ROOM':1,
    'ROOM_CREATED':2,
    'ROOM_CREATED_FAILED':3,
    'MESSAGE_RECEIVED':4,
    'SET_MESSAGE_DELIVERED':5,
    'MESSAGE_DELIVERED':6,
    'GET_BACK_CREATED_MESSAGE':7,
    'SET_LIST_OF_MESSAGE_DELIVERED':8,
    'RECEIVE_LIST_OF_MESSAGE_DELIVERED':9,
    'SET_SEEN_MESSAGE':10,
    'RECEIVE_SEEN_MESSAGE':11,
}


const USER_HANDLES = {
    'NEW_CONNECTION':0,
    'REMOVE_CONNECTION': 1,
}



const MAIN_HANDLERS = {
    'USER_CONFIG':0,
    'FILE_SHARE':1,
    'MESSAGE':2,
}


const FILE_TYPES = {
    'FILE_CREATE':0,
    'FILE_CHUCK_TO_SERVER':1,
    'FILE_CHUCK_TO_CLIENT':2,
    'FILE_CHUCK_FINISHED':3,
    'FILE_CREATED':4
}

const ERRORS = {
    'ROOM_ALREADY_EXISTS':50
}



module.exports = {MESSAGE_TYPES,MAIN_HANDLERS,ERRORS,USER_HANDLES,FILE_TYPES}